# 명시적 인덱서 검색

In [1]:
import pandas as pd
import seaborn as sns

diamonds = sns.load_dataset('diamonds')
diamonds.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

carat: 다이아몬드의 무게를 캐럿(carat) 단위로 나타낸 값입니다. 캐럿은 다이아몬드의 크기를 결정하는 중요한 요소입니다.

cut: 다이아몬드의 컷 등급을 나타내는 값입니다. 컷 등급은 다이아몬드의 연마 품질을 나타내며, 아래와 같은 등급이 포함됩니다:

Fair
Good
Very Good
Premium
Ideal
color: 다이아몬드의 색상 등급을 나타내는 값입니다. 색상 등급은 D (무색)부터 J (약간의 색상)까지의 범위를 가집니다. 일반적으로 D가 가장 높은 등급으로 간주됩니다.

clarity: 다이아몬드의 투명도(clarity) 등급을 나타내는 값입니다. 투명도 등급은 내포물 및 결점의 양에 따라 결정되며, 아래와 같은 등급이 포함됩니다:

I1 (Included)
SI1, SI2 (Slightly Included)
VS1, VS2 (Very Slightly Included)
VVS1, VVS2 (Very Very Slightly Included)
IF (Internally Flawless)
FL (Flawless)
depth: 다이아몬드의 깊이 비율(depth percentage)을 나타낸 값입니다. 이는 다이아몬드의 깊이를 평균 지름으로 나눈 비율로, 다이아몬드의 전체적인 비율과 광학적 성질에 영향을 미칩니다.

table: 다이아몬드의 테이블(table) 비율을 나타낸 값입니다. 이는 다이아몬드의 상단 평평한 면적의 크기를 전체 지름으로 나눈 비율입니다.

price: 다이아몬드의 가격을 미국 달러(USD)로 나타낸 값입니다.

x: 다이아몬드의 길이를 밀리미터(mm) 단위로 나타낸 값입니다.

y: 다이아몬드의 너비를 밀리미터(mm) 단위로 나타낸 값입니다.

z: 다이아몬드의 깊이를 밀리미터(mm) 단위로 나타낸 값입니다.

# loc

데이터프레임을 생성시 부여된 명시적인(explicity) 행, 열 인덱스 정보를 활용해 데이터를 추출하는 방식

* 데이터프레임객체.loc[ 행검색조건 , 열검색조건 ]

첫번째 행 데이터

In [3]:
diamonds.loc[0]

carat       0.23
cut        Ideal
color          E
clarity      SI2
depth       61.5
table       55.0
price        326
x           3.95
y           3.98
z           2.43
Name: 0, dtype: object

In [4]:
diamonds.loc[2]

carat      0.23
cut        Good
color         E
clarity     VS1
depth      56.9
table      65.0
price       327
x          4.05
y          4.07
z          2.31
Name: 2, dtype: object

세번째행의 price열 데이터 조회

In [5]:
diamonds.loc[2,'price']

np.int64(327)

In [8]:
diamonds.loc[3,'clarity']

'VS2'

* 슬라이싱 적용  
[주의] loc에서는 마지막 인덱스를 포함

In [9]:
diamonds.head(26)

    carat        cut color clarity  depth  table  price     x     y     z
0    0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1    0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2    0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3    0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4    0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
5    0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
6    0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
7    0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
8    0.22       Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
9    0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39
10   0.30       Good     J     SI1   64.0   55.0    339  4.25  4.28  2.73
11   0.23      Ideal     J     VS1   62.8   56.0    340  3.93  3.90  2.46
12   0.22    Premium     F     SI1   60.4   61.0    342  3.88  3.84  2.33
13   0.31      Ideal     J     SI2   62.2   54.0    344  4.35  4.37  2.71
14   0.20    Premium     E     SI2   60.2   62.0    345  3.79  3.75  2.27
15   0.32    Premium     E      I1   60.9   58.0    345  4.38  4.42  2.68
16   0.30      Ideal     I     SI2   62.0   54.0    348  4.31  4.34  2.68
17   0.30       Good     J     SI1   63.4   54.0    351  4.23  4.29  2.70
18   0.30       Good     J     SI1   63.8   56.0    351  4.23  4.26  2.71
19   0.30  Very Good     J     SI1   62.7   59.0    351  4.21  4.27  2.66
20   0.30       Good     I     SI2   63.3   56.0    351  4.26  4.30  2.71
21   0.23  Very Good     E     VS2   63.8   55.0    352  3.85  3.92  2.48
22   0.23  Very Good     H     VS1   61.0   57.0    353  3.94  3.96  2.41
23   0.31  Very Good     J     SI1   59.4   62.0    353  4.39  4.43  2.62
24   0.31  Very Good     J     SI1   58.1   62.0    353  4.44  4.47  2.59
25   0.23  Very Good     G    VVS2   60.4   58.0    354  3.97  4.01  2.41

10행에서 25행 사이의 모든 'carat' 데이터 조회

In [16]:
diamonds.loc[10:25,'carat']

10    0.30
11    0.23
12    0.22
13    0.31
14    0.20
15    0.32
16    0.30
17    0.30
18    0.30
19    0.30
20    0.30
21    0.23
22    0.23
23    0.31
24    0.31
25    0.23
Name: carat, dtype: float64

- 단일열을 데이터프레임형태로 반환

In [18]:
diamonds['carat'].head(3)

0    0.23
1    0.21
2    0.23
Name: carat, dtype: float64

* loc에서 펜시검색 적용

In [15]:
diamonds['carat'][10:26]

10    0.30
11    0.23
12    0.22
13    0.31
14    0.20
15    0.32
16    0.30
17    0.30
18    0.30
19    0.30
20    0.30
21    0.23
22    0.23
23    0.31
24    0.31
25    0.23
Name: carat, dtype: float64

# 암묵적(Implicity) 인덱서

* 인덱스 또는 columns이 레이블(문자)로 존재하더라고 암묵적으로 인덱스 접근이 가능
* iloc[행필터링조건, 열필터링조건]
* 암묵적 인덱스는 행 또는 열에 시작이 0부터 시작된다.

* 마이너스 인덱스 활용

In [20]:
diamonds.shape

(53940, 10)

수집한 데이터의 중위수번째(26970)의 데이터를 샘플링하여 조회하고 싶은경우

In [22]:
diamonds.iloc[26970]

carat        1.6
cut        Ideal
color          G
clarity      VS1
depth       62.0
table       54.0
price      17050
x           7.53
y            7.5
z            4.6
Name: 26970, dtype: object

In [24]:
diamonds.columns

Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y',
       'z'],
      dtype='object')

In [28]:
diamonds.iloc[:,2] #행의 조건은 생략할수 없다

0        E
1        E
2        E
3        I
4        J
        ..
53935    D
53936    D
53937    D
53938    H
53939    D
Name: color, Length: 53940, dtype: category
Categories (7, object): ['D', 'E', 'F', 'G', 'H', 'I', 'J']

In [29]:
diamonds.iloc[:,[2]].head()

  color
0     E
1     E
2     E
3     I
4     J

* 마이너스 인덱스 접근  
  마지막 열 조회

In [31]:
diamonds.iloc[:,[-1]]

          z
0      2.43
1      2.31
2      2.31
3      2.63
4      2.75
...     ...
53935  3.50
53936  3.61
53937  3.56
53938  3.74
53939  3.64

[53940 rows x 1 columns]

* 마이너스 인덱스를 활용한 행,열 슬라이싱  
마지막 3개열 중위수부터 10개

In [33]:
diamonds.iloc[26970:26980,-3:]

          x     y     z
0      3.95  3.98  2.43
1      3.89  3.84  2.31
2      4.05  4.07  2.31
3      4.20  4.23  2.63
4      4.34  4.35  2.75
...     ...   ...   ...
53935  5.75  5.76  3.50
53936  5.69  5.75  3.61
53937  5.66  5.68  3.56
53938  6.15  6.12  3.74
53939  5.83  5.87  3.64

[53940 rows x 3 columns]

* 열이름을 통한 슬라이싱

In [34]:
#주의사항] 열이름으로 슬라이싱을 하려는 경우는 열이름이 정렬이 되어 있어야 한다.
diamonds.loc[:,'x':'z'].head()

      x     y     z
0  3.95  3.98  2.43
1  3.89  3.84  2.31
2  4.05  4.07  2.31
3  4.20  4.23  2.63
4  4.34  4.35  2.75

# 인덱스 변경

데이터 분석을 위해 기존의 열의 값을 인덱스로 활용

In [36]:
diamonds.head(60)

    carat        cut color clarity  depth  table  price     x     y     z
0    0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1    0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2    0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3    0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4    0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
5    0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
6    0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
7    0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
8    0.22       Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
9    0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39
10   0.30       Good     J     SI1   64.0   55.0    339  4.25  4.28  2.73
11   0.23      Ideal     J     VS1   62.8   56.0    340  3.93  3.90  2.46
12   0.22    Premium     F     SI1   60.4   61.0    342  3.88  3.84  2.33
13   0.31      Ideal     J     SI2   62.2   54.0    344  4.35  4.37  2.71
14   0.20    Premium     E     SI2   60.2   62.0    345  3.79  3.75  2.27
15   0.32    Premium     E      I1   60.9   58.0    345  4.38  4.42  2.68
16   0.30      Ideal     I     SI2   62.0   54.0    348  4.31  4.34  2.68
17   0.30       Good     J     SI1   63.4   54.0    351  4.23  4.29  2.70
18   0.30       Good     J     SI1   63.8   56.0    351  4.23  4.26  2.71
19   0.30  Very Good     J     SI1   62.7   59.0    351  4.21  4.27  2.66
20   0.30       Good     I     SI2   63.3   56.0    351  4.26  4.30  2.71
21   0.23  Very Good     E     VS2   63.8   55.0    352  3.85  3.92  2.48
22   0.23  Very Good     H     VS1   61.0   57.0    353  3.94  3.96  2.41
23   0.31  Very Good     J     SI1   59.4   62.0    353  4.39  4.43  2.62
24   0.31  Very Good     J     SI1   58.1   62.0    353  4.44  4.47  2.59
25   0.23  Very Good     G    VVS2   60.4   58.0    354  3.97  4.01  2.41
26   0.24    Premium     I     VS1   62.5   57.0    355  3.97  3.94  2.47
27   0.30  Very Good     J     VS2   62.2   57.0    357  4.28  4.30  2.67
28   0.23  Very Good     D     VS2   60.5   61.0    357  3.96  3.97  2.40
29   0.23  Very Good     F     VS1   60.9   57.0    357  3.96  3.99  2.42
30   0.23  Very Good     F     VS1   60.0   57.0    402  4.00  4.03  2.41
31   0.23  Very Good     F     VS1   59.8   57.0    402  4.04  4.06  2.42
32   0.23  Very Good     E     VS1   60.7   59.0    402  3.97  4.01  2.42
33   0.23  Very Good     E     VS1   59.5   58.0    402  4.01  4.06  2.40
34   0.23  Very Good     D     VS1   61.9   58.0    402  3.92  3.96  2.44
35   0.23       Good     F     VS1   58.2   59.0    402  4.06  4.08  2.37
36   0.23       Good     E     VS1   64.1   59.0    402  3.83  3.85  2.46
37   0.31       Good     H     SI1   64.0   54.0    402  4.29  4.31  2.75
38   0.26  Very Good     D     VS2   60.8   59.0    403  4.13  4.16  2.52
39   0.33      Ideal     I     SI2   61.8   55.0    403  4.49  4.51  2.78
40   0.33      Ideal     I     SI2   61.2   56.0    403  4.49  4.50  2.75
41   0.33      Ideal     J     SI1   61.1   56.0    403  4.49  4.55  2.76
42   0.26       Good     D     VS2   65.2   56.0    403  3.99  4.02  2.61
43   0.26       Good     D     VS1   58.4   63.0    403  4.19  4.24  2.46
44   0.32       Good     H     SI2   63.1   56.0    403  4.34  4.37  2.75
45   0.29    Premium     F     SI1   62.4   58.0    403  4.24  4.26  2.65
46   0.32  Very Good     H     SI2   61.8   55.0    403  4.35  4.42  2.71
47   0.32       Good     H     SI2   63.8   56.0    403  4.36  4.38  2.79
48   0.25  Very Good     E     VS2   63.3   60.0    404  4.00  4.03  2.54
49   0.29  Very Good     H     SI2   60.7   60.0    404  4.33  4.37  2.64
50   0.24  Very Good     F     SI1   60.9   61.0    404  4.02  4.03  2.45
51   0.23      Ideal     G     VS1   61.9   54.0    404  3.93  3.95  2.44
52   0.32      Ideal     I     SI1   60.9   55.0    404  4.45  4.48  2.72
53   0.22    Premium     E     VS2   61.6   58.0    404  3.93  3.89  2.41
54   0.22    Premium     D     VS2   59.3   62.0    404  3.91  3.88  2.31
55   0.30      Ideal     I     SI2   61.0   59.0    405  4.30  4.33  2.63
56   0.30    Premium     J     SI2   59.3   61.0    405  4.43  4.38  2.61
57   0.30  Very Good     I     SI1   62.6   57.0    405  4.25  4.28  2.67
58   0.30  Very Good     I     SI1   63.0   57.0    405  4.28  4.32  2.71
59   0.30       Good     I     SI1   63.2   55.0    405  4.25  4.29  2.70

In [40]:
set_i =diamonds.set_index('color').head(20)
set_i

       carat        cut clarity  depth  table  price     x     y     z
color
E       0.23      Ideal     SI2   61.5   55.0    326  3.95  3.98  2.43
E       0.21    Premium     SI1   59.8   61.0    326  3.89  3.84  2.31
E       0.23       Good     VS1   56.9   65.0    327  4.05  4.07  2.31
I       0.29    Premium     VS2   62.4   58.0    334  4.20  4.23  2.63
J       0.31       Good     SI2   63.3   58.0    335  4.34  4.35  2.75
J       0.24  Very Good    VVS2   62.8   57.0    336  3.94  3.96  2.48
I       0.24  Very Good    VVS1   62.3   57.0    336  3.95  3.98  2.47
H       0.26  Very Good     SI1   61.9   55.0    337  4.07  4.11  2.53
E       0.22       Fair     VS2   65.1   61.0    337  3.87  3.78  2.49
H       0.23  Very Good     VS1   59.4   61.0    338  4.00  4.05  2.39
J       0.30       Good     SI1   64.0   55.0    339  4.25  4.28  2.73
J       0.23      Ideal     VS1   62.8   56.0    340  3.93  3.90  2.46
F       0.22    Premium     SI1   60.4   61.0    342  3.88  3.84  2.33
J       0.31      Ideal     SI2   62.2   54.0    344  4.35  4.37  2.71
E       0.20    Premium     SI2   60.2   62.0    345  3.79  3.75  2.27
E       0.32    Premium      I1   60.9   58.0    345  4.38  4.42  2.68
I       0.30      Ideal     SI2   62.0   54.0    348  4.31  4.34  2.68
J       0.30       Good     SI1   63.4   54.0    351  4.23  4.29  2.70
J       0.30       Good     SI1   63.8   56.0    351  4.23  4.26  2.71
J       0.30  Very Good     SI1   62.7   59.0    351  4.21  4.27  2.66

In [41]:
set_i.sort_index().head(20) #인덱스를 정렬한 결과를 데이터 프레임으로 변환, 자기자신은 변경X

       carat        cut clarity  depth  table  price     x     y     z
color
E       0.23      Ideal     SI2   61.5   55.0    326  3.95  3.98  2.43
E       0.21    Premium     SI1   59.8   61.0    326  3.89  3.84  2.31
E       0.23       Good     VS1   56.9   65.0    327  4.05  4.07  2.31
E       0.32    Premium      I1   60.9   58.0    345  4.38  4.42  2.68
E       0.20    Premium     SI2   60.2   62.0    345  3.79  3.75  2.27
E       0.22       Fair     VS2   65.1   61.0    337  3.87  3.78  2.49
F       0.22    Premium     SI1   60.4   61.0    342  3.88  3.84  2.33
H       0.23  Very Good     VS1   59.4   61.0    338  4.00  4.05  2.39
H       0.26  Very Good     SI1   61.9   55.0    337  4.07  4.11  2.53
I       0.24  Very Good    VVS1   62.3   57.0    336  3.95  3.98  2.47
I       0.29    Premium     VS2   62.4   58.0    334  4.20  4.23  2.63
I       0.30      Ideal     SI2   62.0   54.0    348  4.31  4.34  2.68
J       0.30       Good     SI1   63.8   56.0    351  4.23  4.26  2.71
J       0.30       Good     SI1   64.0   55.0    339  4.25  4.28  2.73
J       0.23      Ideal     VS1   62.8   56.0    340  3.93  3.90  2.46
J       0.24  Very Good    VVS2   62.8   57.0    336  3.94  3.96  2.48
J       0.31      Ideal     SI2   62.2   54.0    344  4.35  4.37  2.71
J       0.31       Good     SI2   63.3   58.0    335  4.34  4.35  2.75
J       0.30       Good     SI1   63.4   54.0    351  4.23  4.29  2.70
J       0.30  Very Good     SI1   62.7   59.0    351  4.21  4.27  2.66

* 인덱스 정렬

In [43]:
sorted_set_i = set_i.sort_index().head(20)

* 인덱스 정렬 후 인덱스 기반 행데이터 필터링

E-F등급 다이아몬드 데이터 추출

In [44]:
sorted_set_i.loc['E':'F'].head(20)

       carat      cut clarity  depth  table  price     x     y     z
color
E       0.23    Ideal     SI2   61.5   55.0    326  3.95  3.98  2.43
E       0.21  Premium     SI1   59.8   61.0    326  3.89  3.84  2.31
E       0.23     Good     VS1   56.9   65.0    327  4.05  4.07  2.31
E       0.32  Premium      I1   60.9   58.0    345  4.38  4.42  2.68
E       0.20  Premium     SI2   60.2   62.0    345  3.79  3.75  2.27
E       0.22     Fair     VS2   65.1   61.0    337  3.87  3.78  2.49
F       0.22  Premium     SI1   60.4   61.0    342  3.88  3.84  2.33

In [ ]:
정렬되지 않은 경우 => error

In [45]:
#set_i.loc['E':'F'].head(20)

KeyError: "Cannot get left slice bound for non-unique label: 'E'"

* 열의 순서 바꾸기

In [54]:
diamonds.columns

Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y',
       'z'],
      dtype='object')

기존 열에서 price열을 제일 앞에 정의하고 싶을 경우

In [55]:
diamonds.columns = ['price', 'carat', 'cut', 'color', 'clarity', 'depth', 'table', 'x', 'y', 'z']
diamonds

       price      carat cut color  clarity  depth  table     x     y     z
0       0.23      Ideal   E   SI2     61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium   E   SI1     59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good   E   VS1     56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium   I   VS2     62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good   J   SI2     63.3   58.0    335  4.34  4.35  2.75
...      ...        ...  ..   ...      ...    ...    ...   ...   ...   ...
53935   0.72      Ideal   D   SI1     60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good   D   SI1     63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good   D   SI1     62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium   H   SI2     61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal   D   SI2     62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [59]:
diamonds.columns =['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y', 'z']

In [62]:
diamonds_priority = diamonds[['price', 'carat', 'cut', 'color', 'clarity', 'depth', 'table', 'x', 'y','z']]
diamonds_priority

       price  carat        cut color clarity  depth  table     x     y     z
0        326   0.23      Ideal     E     SI2   61.5   55.0  3.95  3.98  2.43
1        326   0.21    Premium     E     SI1   59.8   61.0  3.89  3.84  2.31
2        327   0.23       Good     E     VS1   56.9   65.0  4.05  4.07  2.31
3        334   0.29    Premium     I     VS2   62.4   58.0  4.20  4.23  2.63
4        335   0.31       Good     J     SI2   63.3   58.0  4.34  4.35  2.75
...      ...    ...        ...   ...     ...    ...    ...   ...   ...   ...
53935   2757   0.72      Ideal     D     SI1   60.8   57.0  5.75  5.76  3.50
53936   2757   0.72       Good     D     SI1   63.1   55.0  5.69  5.75  3.61
53937   2757   0.70  Very Good     D     SI1   62.8   60.0  5.66  5.68  3.56
53938   2757   0.86    Premium     H     SI2   61.0   58.0  6.15  6.12  3.74
53939   2757   0.75      Ideal     D     SI2   62.2   55.0  5.83  5.87  3.64

[53940 rows x 10 columns]

In [63]:
diamonds_priority.loc[:,'price':'cut']

       price  carat        cut
0        326   0.23      Ideal
1        326   0.21    Premium
2        327   0.23       Good
3        334   0.29    Premium
4        335   0.31       Good
...      ...    ...        ...
53935   2757   0.72      Ideal
53936   2757   0.72       Good
53937   2757   0.70  Very Good
53938   2757   0.86    Premium
53939   2757   0.75      Ideal

[53940 rows x 3 columns]

In [ ]:
ms_prior

* 열 이름으로 필터링 할 경우에는 열 이름까지 정렬할 필요는 없다.  
  왜냐하면 열이름은 중복이 허용되지 않기 때문이다.